const provData1 = {
	nodes: [{ id: 'trial1', label: 'Trial 1', type: 'experiment', time: 1 }],
	links: [],
};

const provData2 = {
	nodes: [
		...provData1.nodes,
		{ id: 'sow1', label: 'Sow', type: 'activity', time: 1 },
		{ id: 'plot1', label: 'Plot 1', type: 'entity', time: 1 },
		{ id: 'plot2', label: 'Plot 2', type: 'entity', time: 1 },
		{ id: 'plot3', label: 'Plot 3', type: 'entity', time: 1 },
		{ id: 'plot4', label: 'Plot 4', type: 'entity', time: 1 },
		{ id: 'plot5', label: 'Plot 5', type: 'entity', time: 1 },
		{ id: 'plot6', label: 'Plot 6', type: 'entity', time: 1 },
		{ id: 'plot7', label: 'Plot 7', type: 'entity', time: 1 },
		{ id: 'plot8', label: 'Plot 8', type: 'entity', time: 1 },
		{ id: 'plot9', label: 'Plot 9', type: 'entity', time: 1 },
		{ id: 'plot10', label: 'Plot 10', type: 'entity', time: 1 },
		{ id: 'plot11', label: 'Plot 11', type: 'entity', time: 1 },
		{ id: 'plot12', label: 'Plot 12', type: 'entity', time: 1 },
		{ id: 'plot13', label: 'Plot 13', type: 'entity', time: 1 },
		{ id: 'plot14', label: 'Plot 14', type: 'entity', time: 1 },
		{ id: 'plot15', label: 'Plot 15', type: 'entity', time: 1 },
		{ id: 'plot16', label: 'Plot 16', type: 'entity', time: 1 },
		{ id: 'plot17', label: 'Plot 17', type: 'entity', time: 1 },
		{ id: 'plot18', label: 'Plot 18', type: 'entity', time: 1 },
		{ id: 'plot19', label: 'Plot 19', type: 'entity', time: 1 },
		{ id: 'plot20', label: 'Plot 20', type: 'entity', time: 1 },
	],
	links: [
		{ source: 'trial1', target: 'sow1', label: 'wasInformedBy' },
		{ source: 'sow1', target: 'plot1', label: 'wasGeneratedBy' },
		{ source: 'sow1', target: 'plot2' },
		{ source: 'sow1', target: 'plot3' },
		{ source: 'sow1', target: 'plot4' },
		{ source: 'sow1', target: 'plot5' },
		{ source: 'sow1', target: 'plot6' },
		{ source: 'sow1', target: 'plot7' },
		{ source: 'sow1', target: 'plot8' },
		{ source: 'sow1', target: 'plot9' },
		{ source: 'sow1', target: 'plot10' },
		{ source: 'sow1', target: 'plot11' },
		{ source: 'sow1', target: 'plot12' },
		{ source: 'sow1', target: 'plot13' },
		{ source: 'sow1', target: 'plot14' },
		{ source: 'sow1', target: 'plot15' },
		{ source: 'sow1', target: 'plot16' },
		{ source: 'sow1', target: 'plot17' },
		{ source: 'sow1', target: 'plot18' },
		{ source: 'sow1', target: 'plot19' },
		{ source: 'sow1', target: 'plot20' },
	],
};

const provData3 = {
	nodes: [
		...provData2.nodes,
		{ id: 'harvest1', label: 'Harvest', type: 'activity', time: 2 },
		{ id: 'seed1', label: 'Seed 1', type: 'entity', time: 2 },
		{ id: 'seed2', label: 'Seed 2', type: 'entity', time: 2 },
		{ id: 'seed3', label: 'Seed 3', type: 'entity', time: 2 },
		{ id: 'seed4', label: 'Seed 4', type: 'entity', time: 2 },
		{ id: 'seed5', label: 'Seed 5', type: 'entity', time: 2 },
		{ id: 'seed6', label: 'Seed 6', type: 'entity', time: 2 },
		{ id: 'seed7', label: 'Seed 7', type: 'entity', time: 2 },
		{ id: 'seed8', label: 'Seed 8', type: 'entity', time: 2 },
		{ id: 'seed9', label: 'Seed 9', type: 'entity', time: 2 },
		{ id: 'seed10', label: 'Seed 10', type: 'entity', time: 2 },
		{ id: 'seed11', label: 'Seed 11', type: 'entity', time: 2 },
		{ id: 'seed12', label: 'Seed 12', type: 'entity', time: 2 },
		{ id: 'seed13', label: 'Seed 13', type: 'entity', time: 2 },
		{ id: 'seed14', label: 'Seed 14', type: 'entity', time: 2 },
		{ id: 'seed15', label: 'Seed 15', type: 'entity', time: 2 },
		{ id: 'seed16', label: 'Seed 16', type: 'entity', time: 2 },
		{ id: 'seed17', label: 'Seed 17', type: 'entity', time: 2 },
		{ id: 'seed18', label: 'Seed 18', type: 'entity', time: 2 },
		{ id: 'seed19', label: 'Seed 19', type: 'entity', time: 2 },
		{ id: 'seed20', label: 'Seed 20', type: 'entity', time: 2 },
	],
	links: [
		...provData2.links,
		{ source: 'trial1', target: 'harvest1', label: 'wasInformedBy' },
		{ source: 'harvest1', target: 'seed1', label: 'wasGeneratedBy' },
		{ source: 'harvest1', target: 'seed2' },
		{ source: 'harvest1', target: 'seed3' },
		{ source: 'harvest1', target: 'seed4' },
		{ source: 'harvest1', target: 'seed5' },
		{ source: 'harvest1', target: 'seed6' },
		{ source: 'harvest1', target: 'seed7' },
		{ source: 'harvest1', target: 'seed8' },
		{ source: 'harvest1', target: 'seed9' },
		{ source: 'harvest1', target: 'seed10' },
		{ source: 'harvest1', target: 'seed11' },
		{ source: 'harvest1', target: 'seed12' },
		{ source: 'harvest1', target: 'seed13' },
		{ source: 'harvest1', target: 'seed14' },
		{ source: 'harvest1', target: 'seed15' },
		{ source: 'harvest1', target: 'seed16' },
		{ source: 'harvest1', target: 'seed17' },
		{ source: 'harvest1', target: 'seed18' },
		{ source: 'harvest1', target: 'seed19' },
		{ source: 'harvest1', target: 'seed20' },
		{ source: 'plot1', target: 'seed1', label: 'derivedFrom' },
		{ source: 'plot2', target: 'seed2' },
		{ source: 'plot3', target: 'seed3' },
		{ source: 'plot4', target: 'seed4' },
		{ source: 'plot5', target: 'seed5' },
		{ source: 'plot6', target: 'seed6' },
		{ source: 'plot7', target: 'seed7' },
		{ source: 'plot8', target: 'seed8' },
		{ source: 'plot9', target: 'seed9' },
		{ source: 'plot10', target: 'seed10' },
		{ source: 'plot11', target: 'seed11' },
		{ source: 'plot12', target: 'seed12' },
		{ source: 'plot13', target: 'seed13' },
		{ source: 'plot14', target: 'seed14' },
		{ source: 'plot15', target: 'seed15' },
		{ source: 'plot16', target: 'seed16' },
		{ source: 'plot17', target: 'seed17' },
		{ source: 'plot18', target: 'seed18' },
		{ source: 'plot19', target: 'seed19' },
		{ source: 'plot20', target: 'seed20' },
	],
};

const provData4 = {
	nodes: [
		...provData3.nodes,
		{ id: 'trial2', label: 'Trial 2', type: 'experiment', time: 4 },
		{ id: 'sow2', label: 'Sow', type: 'activity', time: 4 },
		{ id: 'plotB1', label: 'Plot B1', type: 'entity', time: 4 },
		{ id: 'plotB2', label: 'Plot B2', type: 'entity', time: 4 },
		{ id: 'plotB3', label: 'Plot B3', type: 'entity', time: 4 },
		{ id: 'plotB4', label: 'Plot B4', type: 'entity', time: 4 },
		{ id: 'plotB5', label: 'Plot B5', type: 'entity', time: 4 },
		{ id: 'plotB6', label: 'Plot B6', type: 'entity', time: 4 },
		{ id: 'plotB7', label: 'Plot B7', type: 'entity', time: 4 },
		{ id: 'plotB8', label: 'Plot B8', type: 'entity', time: 4 },
		{ id: 'plotB9', label: 'Plot B9', type: 'entity', time: 4 },
		{ id: 'plotB10', label: 'Plot B10', type: 'entity', time: 4 },
		{ id: 'plotB11', label: 'Plot B11', type: 'entity', time: 4 },
		{ id: 'plotB12', label: 'Plot B12', type: 'entity', time: 4 },
		{ id: 'plotB13', label: 'Plot B13', type: 'entity', time: 4 },
		{ id: 'plotB14', label: 'Plot B14', type: 'entity', time: 4 },
		{ id: 'plotB15', label: 'Plot B15', type: 'entity', time: 4 },
		{ id: 'plotB16', label: 'Plot B16', type: 'entity', time: 4 },
		{ id: 'plotB17', label: 'Plot B17', type: 'entity', time: 4 },
		{ id: 'plotB18', label: 'Plot B18', type: 'entity', time: 4 },
		{ id: 'plotB19', label: 'Plot B19', type: 'entity', time: 4 },
		{ id: 'plotB20', label: 'Plot B20', type: 'entity', time: 4 },
	],
	links: [
		...provData3.links,
		{ source: 'trial1', target: 'trial2', label: 'wasInformedBy' },
		{ source: 'trial2', target: 'sow2', label: 'wasInformedBy' },
		{ source: 'sow2', target: 'plotB1', label: 'wasGeneratedBy' },
		{ source: 'sow2', target: 'plotB2' },
		{ source: 'sow2', target: 'plotB3' },
		{ source: 'sow2', target: 'plotB4' },
		{ source: 'sow2', target: 'plotB5' },
		{ source: 'sow2', target: 'plotB6' },
		{ source: 'sow2', target: 'plotB7' },
		{ source: 'sow2', target: 'plotB8' },
		{ source: 'sow2', target: 'plotB9' },
		{ source: 'sow2', target: 'plotB10' },
		{ source: 'sow2', target: 'plotB11' },
		{ source: 'sow2', target: 'plotB12' },
		{ source: 'sow2', target: 'plotB13' },
		{ source: 'sow2', target: 'plotB14' },
		{ source: 'sow2', target: 'plotB15' },
		{ source: 'sow2', target: 'plotB16' },
		{ source: 'sow2', target: 'plotB17' },
		{ source: 'sow2', target: 'plotB18' },
		{ source: 'sow2', target: 'plotB19' },
		{ source: 'sow2', target: 'plotB20' },
		{ source: 'seed1', target: 'plotB1', label: 'derivedFrom' },
		{ source: 'seed2', target: 'plotB2' },
		{ source: 'seed3', target: 'plotB3' },
		{ source: 'seed4', target: 'plotB4' },
		{ source: 'seed5', target: 'plotB5' },
		{ source: 'seed6', target: 'plotB6' },
		{ source: 'seed7', target: 'plotB7' },
		{ source: 'seed8', target: 'plotB8' },
		{ source: 'seed9', target: 'plotB9' },
		{ source: 'seed10', target: 'plotB10' },
		{ source: 'seed11', target: 'plotB11' },
		{ source: 'seed12', target: 'plotB12' },
		{ source: 'seed13', target: 'plotB13' },
		{ source: 'seed14', target: 'plotB14' },
		{ source: 'seed15', target: 'plotB15' },
		{ source: 'seed16', target: 'plotB16' },
		{ source: 'seed17', target: 'plotB17' },
		{ source: 'seed18', target: 'plotB18' },
		{ source: 'seed19', target: 'plotB19' },
		{ source: 'seed20', target: 'plotB20' },
	],
};

const provData5 = {
	nodes: [
		...provData4.nodes,
		{ id: 'observation1', label: 'Plant height', type: 'observation', time: 1 },
		{ id: 'observation2', label: 'Grain weight', type: 'observation', time: 2 },
		{
			id: 'observation3',
			label: 'Leaf area',
			type: 'observation',
			time: 4,
		},
	],
	links: [
		...provData4.links,
		{ source: 'plot1', target: 'observation1', label: 'observed' },
		{ source: 'seed1', target: 'observation2', label: 'observed' },
		{ source: 'plotB1', target: 'observation3', label: 'observed' },
	],
};

export { provData1, provData2, provData3, provData4, provData5 };
